### ISSUE TITLE
COMMITTEES

### ISSUE THREAD

**Issue by andrewjong** [mlatsjsu/Website#38]
Here is the text for committees below, and some pictures. Can resize/crop the pictures to what you think looks best.
# Committees
Our meetings alternate between _Committee Days_ and _Club Days_. Committee Days let members become experts in their topic of interest, while Club Days promote symbiotic learning as a community.

- **Committee Days**: Members work within their committee to learn, share resources, and complete projects as a team.
- **Club Days**: Committees rotate to host workshops, paper readings, presentations, or fun games (e.g. trivia) for symbiotic club learning. Learners are exposed to important concepts from other AI areas, and presenters refine their knowledge by teaching others.

## Computer Vision Committee
![image](https://user-images.githubusercontent.com/8121216/76156091-1ae2cf00-60aa-11ea-94d1-e15d9451098a.png)

The Computer Vision committee is dedicated to retrieve, process, and analyze information from the visual world with deep learning. Our main focus is on object recognition and classification using a variety of convolutional neural networks. We aim to gain expertise in vision models through hands-on experience.

## Reinforcement Learning Committee
![image](https://user-images.githubusercontent.com/8121216/76156071-d5be9d00-60a9-11ea-99f3-76ef8d9de90d.png)

Reinforcement learning teaches an agent how to make decisions through learned experience in the real world or simulation. Applications include game playing, robotics and self driving cars. The RL committee uses projects and case studies to teach members actionable skills.

## Graphics Committee
![image](https://user-images.githubusercontent.com/8121216/76156097-2930eb00-60aa-11ea-9cbb-cabd30645f4c.png)

The Graphics committee explores deep learning for generative graphics, i.e. with Generative Adversarial Networks. These topics include interactive rendering, visualization, art, as well as virtual and augmented reality applications. We aim to use AI to enhance visual imagination. Members will gain practical implementation and research skills through projects.

## Natural Language Committee
![image](https://user-images.githubusercontent.com/8121216/76156064-c3446380-60a9-11ea-8e92-9972df13d574.png)
![image](https://user-images.githubusercontent.com/8121216/76156074-e242f580-60a9-11ea-9ef0-ef6cae6ab969.png)
The Natural Language Processing committee explores problems related to human language and cognition using traditional Computational Linguistics techniques, Machine Learning and Deep Learning algorithms. We encourage learning by doing projects at each meeting; we discuss various approaches in NLP to tackle the problem at hand. Members will gain insights of NLP ranging from basics of text pre-processing to understanding state of the art research in NLP.

## Traditional ML Committee
![image](https://user-images.githubusercontent.com/8121216/76156210-c50f2680-60ab-11ea-90f9-e71df4ba7572.png)

The Traditional Machine Learning committee encompasses traditional machine learning models such as K-Nearest Neighbors, Random Forests, and SVMs as well as machine learning techniques like hyperparameter optimization, dimensionality reduction, and cross-validation. We seek to gain knowledge about techniques that benefit both traditional machine learning and deep learning.

**Comment by tintheanh** [comment]
Can a member belong to more than one committees?

**Comment by andrewjong** [comment]
Possibly yes, though rare.

**Comment by andrewjong** [comment]
Thanks for working on it!

**Comment by tintheanh** [comment]
Also, one committee has one leader by default?

**Comment by andrewjong** [comment]
Hm better to have the option to add multiple leaders. Our RL Committee leads are both Jason Do and Gaurav Kuppa. Our NLP leads are Chinmay and Jing.

**Comment by tintheanh** [comment]
Sorry I forgot to ask. Can one be leader of multiple committees at once?

**Comment by andrewjong** [comment]
Nope

**Comment by andrewjong** [comment]
implemented
